version: '3'

services:
  db:
    build: ./mysql
    ports:
      - "8081:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
      MYSQL_DATABASE: studentdb

  web:
    build: ./html
    ports:
      - "8080:80"
    depends_on:
      - db
